# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $entityManager: '@doctrine.orm.entity_manager'
      $connection: '@doctrine.dbal.default_connection'
      $projectDir: '%kernel.project_dir%'

  App\Twig\ConstExtension:
    tags: [ 'twig.extension' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Services\ApiFormatter:
    public: true

  App\Command\:
    resource: '../src/Command'
    tags: [ 'console.command' ]

  App\DataFixtures\RecipeFixtures:
    arguments:
      $projectDir: '%kernel.project_dir%'